<<<<<<< HEAD
# Generated by Django 5.2.9 on 2025-12-06 09:52
=======
# Generated by Django 6.0 on 2025-12-05 21:53
>>>>>>> 2014a9498c4241ae716d6c176e77ae9738d34f37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='Teacherinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 2014a9498c4241ae716d6c176e77ae9738d34f37
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
